### ISSUE TITLE
Weird converter errors, only shows up in console

### ISSUE THREAD

**Issue by FridiNaTor1** [LBPUnion/ProjectLighthouse#133]
Here an error I get there are many of them, when the server starts.

`Error while converting 5272ab04d4c248ee7efb5711b4bbf91b51689dac:
ICSharpCode.SharpZipLib.SharpZipBaseException: Header checksum illegal
   at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.DecodeHeader()
   at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.Decode()
   at ICSharpCode.SharpZipLib.Zip.Compression.Inflater.Inflate(Byte[] buffer, Int32 offset, Int32 count)
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.TextureToPNG(String hash, BinaryReader reader) in /home/LBPSERVER/light/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 84
   at LBPUnion.ProjectLighthouse.Helpers.ImageHelper.LbpFileToPNG(Byte[] data, String hash, LbpFileType type) in /home/LBPSERVER/light/project-lighthouse/ProjectLighthouse/Helpers/ImageHelper.cs:line 42`

**Comment by jvyden** [comment]
That file is broken. Sorry, not much can be done about that.

**Comment by FridiNaTor1** [comment]
> That file is broken. Sorry, not much can be done about that.

So should I delete the files?

**Comment by jvyden** [comment]
Yes.
