### ISSUE TITLE
Attempting to delete a user results in an error code 500.

### ISSUE THREAD

**Issue by m88youngling** [LBPUnion/ProjectLighthouse#643]
**Describe the bug**
Whenever I attempt to delete a user from the website via the admin panel, the resulting page is an error code 500.

**To Reproduce**
1. Go to the admin panel. 
2. Type in the user you want to delete. 
3. Press enter or click submit. 
4. The resulting page is an error code 500 and the user will not be deleted. 

**Expected behavior**
I believe the resulting page is a refreshed admin panel with a success console message at the top of the screen. The user is then deleted. 

**Additional context**
It's sometimes necessary for us to delete accounts in the event of user request or if a test account needs to be deleted.

**Comment by sudokoko** [comment]
Are there any logs that may suggest where the issue lies? I'd be happy to look in to it once I'm home.

**Comment by m88youngling** [comment]
Probably, but I won't be back until like 7:00 this evening, so I suggest asking Ritchie or Slendy to check if you want to check sooner

**Comment by sudokoko** [comment]
Gotcha. I'll see what I can find out.

**Comment by m88youngling** [comment]
Here's the data from the log. I talked to Slendy about it briefly on Discord. He says that "if you try to remove a user with a case against them or a case by them it fails. Then with most of the workarounds you end up either a. Losing the case and all details about it or b. Losing detail of who created the case/who the case was against"

this sounds to me like the user deletion system, or the way moderation cases are handled, need to be rewritten or re-implemented.

```
[01/22/2023-01:13:08.536] [Website] [Microsoft.AspNetCore.Server.Kestrel:Error] <ExecutionContext:RunInternal> Connection id "0HMNR6CQOKIRM", Request id "0HMNR6CQOKIRM:00000001": An unhandled exception was thrown by the application.
[01/22/2023-01:13:08.542] [Website] [Microsoft.AspNetCore.Server.Kestrel:Error] <ExecutionContext:RunInternal> Entries = System.Collections.Generic.List`1[Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry]
TargetSite = Void MoveNext()
Message = The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
Data = System.Collections.ListDictionaryInternal
InnerException =
HelpLink =
Source = Microsoft.EntityFrameworkCore.Relational
HResult = -2146233088
StackTrace =    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyExceptionAsync(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnlyAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at LBPUnion.ProjectLighthouse.Database.RemoveUser(User user) in /srv/lighthouse/project-lighthouse/ProjectLighthouse/Database.cs:line 538
   at LBPUnion.ProjectLighthouse.Administration.Maintenance.Commands.DeleteUserCommand.Run(String[] args, Logger logger) in /srv/lighthouse/project-lighthouse/ProjectLighthouse/Administration/Maintenance/Commands/DeleteUserCommand.cs:line 36
   at LBPUnion.ProjectLighthouse.Administration.Maintenance.MaintenanceHelper.RunCommand(String[] args) in /srv/lighthouse/project-lighthouse/ProjectLighthouse/Administration/Maintenance/MaintenanceHelper.cs:line 60
   at LBPUnion.ProjectLighthouse.Servers.Website.Pages.Admin.AdminPanelPage.OnGet(String args, String command, String maintenanceJob, String log) in /srv/lighthouse/project-lighthouse/ProjectLighthouse.Servers.Website/Pages/Admin/AdminPanelPage.cshtml.cs:line 57
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at LBPUnion.ProjectLighthouse.Middlewares.RateLimitMiddleware.InvokeAsync(HttpContext ctx, Database database) in /srv/lighthouse/project-lighthouse/ProjectLighthouse/Middlewares/RateLimitMiddleware.cs:line 65
   at LBPUnion.ProjectLighthouse.Servers.Website.Middlewares.UserRequiredRedirectMiddleware.InvokeAsync(HttpContext ctx, Database database) in /srv/lighthouse/project-lighthouse/ProjectLighthouse.Servers.Website/Middlewares/UserRequiredRedirectMiddleware.cs:line 98
   at LBPUnion.ProjectLighthouse.Middlewares.RequestLogMiddleware.InvokeAsync(HttpContext ctx) in /srv/lighthouse/project-lighthouse/ProjectLighthouse/Middlewares/RequestLogMiddleware.cs:line 45
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```
